### ISSUE TITLE
0.23.0 compilation error on RPi400 (stable-armv7-unknown-linux-gnueabihf)

### ISSUE THREAD

**Issue by mateusz-szczyrzyca** [bytebeamio/rumqtt#731]
# Expected Behavior

New version (0.23.0) should compile as previous version - example code looks the same.

Platform: Raspbian GNU/Linux 11 \n \l (Raspberry Pi400)
Rustc: `rustc 1.73.0 (cc66ad468 2023-10-03)` - `stable-armv7-unknown-linux-gnueabihf`

# Current Behavior

Does not compile with version bumped to 0.23.0 - some kind of problem with rusttls which I don't use directly in my project.

# Failure Information (for bugs)

```
error[E0599]: no method named `add_trust_anchors` found for struct `RootCertStore` in the current scope
  --> /home/pi/.cargo/registry/src/index.crates.io-1cd66030c949c28d/rumqttc-0.23.0/src/tls.rs:93:29
   |
93 |             root_cert_store.add_trust_anchors(trust_anchors);
   |                             ^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `add_server_trust_anchors`

error[E0599]: no method named `with_client_auth_cert` found for struct `ConfigBuilder` in the current scope
   --> /home/pi/.cargo/registry/src/index.crates.io-1cd66030c949c28d/rumqttc-0.23.0/src/tls.rs:130:24
    |
130 |                 config.with_client_auth_cert(certs, PrivateKey(key))?
    |                        ^^^^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `with_no_client_auth`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `rumqttc` (lib) due to 2 previous errors
```

## Context

0.22.0 - works
0.23.0 - compilation error (cargo clean does not change it)

## Failure Logs

Pasted.

**Comment by swanandx** [comment]
Thanks for reporting, cargo clippy was showing that those functions are deprecated and therefore they were replaced in PR #710 . 
I wonder why it's not working for armv7 though, will investigate it further and get back to you!

**Comment by swanandx** [comment]
can you also try `cargo update` just to be sure and if possible, can you please provide minimal example? Thanks 😁

**Comment by mateusz-szczyrzyca** [comment]
Ok, `cargo update` solved this issue on 0.23.0, I don't know why as I previously did `cargo clean`

This is a very basic example from my project (this code has not been changed between 0.22.0 and 0.23.0:

```
let mut mqttoptions = MqttOptions::new(
        config.mqtt_client_name,
        config.mqtt_broker_host,
        config.mqtt_broker_port,
    );
    mqttoptions.set_keep_alive(Duration::from_secs(MQTT_KEEP_ALIVE));

    let topics: Vec<String> = vec![
        "test1".to_string(),
        "test2".to_string(),
        "test3".to_string(),
    ];
```

**Comment by swanandx** [comment]
> cargo update solved this issue on 0.23.0
>

If it's solved, can we close the issue?
